import { useRef } from 'react';
import type { FileNode, Host, TransferItem } from '../types';
import { Icon, IconButton } from './Ui';

type FileProps = { files: FileNode[]; selected: string; expanded: Set<string>; select: (id: string) => void; toggle: (id: string) => void };
function TreeNodes({ files, selected, expanded, select, toggle }: FileProps) {
  return <ul className="file-tree">{files.map(file => <li key={file.id}><button className={`file-row ${selected === file.id ? 'selected' : ''}`} aria-expanded={file.kind === 'folder' ? expanded.has(file.id) : undefined} onClick={() => { select(file.id); if (file.kind === 'folder') toggle(file.id); }}><span className="tree-chevron">{file.kind === 'folder' && <Icon name={expanded.has(file.id) ? 'down' : 'right'} size={12} />}</span><Icon name={file.kind === 'folder' ? 'folder' : 'file'} className={file.kind === 'folder' ? 'folder-icon' : ''} /><span>{file.name}</span></button>{file.kind === 'folder' && expanded.has(file.id) && (file.children?.length ? <TreeNodes files={file.children} selected={selected} expanded={expanded} select={select} toggle={toggle} /> : <span className="empty-folder">空文件夹</span>)}</li>)}</ul>;
}
export function ConnectionSidebar(props: FileProps & { hosts: Host[]; hostId?: string | null; chooseHost: (id: string) => void; transfers: TransferItem[]; upload: (files: FileList) => void; refresh: () => void; create: () => void; copy: (text: string) => void; notify: (text: string) => void }) {
  const uploadRef = useRef<HTMLInputElement>(null);
  return <aside className="connection-sidebar"><section id="files" className="files-section" tabIndex={-1}><div className="section-heading"><h2>远程文件</h2><div className="inline-actions"><IconButton icon="refresh" label="刷新文件树" onClick={props.refresh} /><IconButton icon="upload" label="选择上传文件" onClick={() => uploadRef.current?.click()} /></div></div><div className="path-bar"><Icon name="home" size={16} /><span>/</span><span>var</span><span>/</span><span>www</span><span>/</span><span>app</span><IconButton icon="copy" label="复制远程路径" onClick={() => props.copy('/var/www/app')} /></div><div className="file-toolbar"><button className="outlined-button" onClick={() => uploadRef.current?.click()}><Icon name="upload" size={17} />上传</button><button className="outlined-button" onClick={props.create}><Icon name="plus" size={19} />新建<Icon name="down" size={14} /></button><IconButton className="outlined-button" icon="more" label="文件更多操作" onClick={() => props.notify('文件操作在内存中模拟；刷新文件树可恢复初始内容。')} /></div><input ref={uploadRef} className="visually-hidden" type="file" multiple aria-label="上传文件选择器" onChange={e => { if (e.target.files?.length) props.upload(e.target.files); e.target.value = ''; }} /><div className="file-tree-scroll"><TreeNodes {...props} /></div></section><div className="transfers"><h3>部署包</h3>{props.transfers.slice(-2).map(transfer => <div className="transfer" key={transfer.id}><div><Icon name="file" size={19} /><span title={transfer.name}>{transfer.name}</span><small>{transfer.progress === 100 ? '已完成' : `${transfer.progress}%`}</small>{transfer.progress === 100 && <span className="small-check"><Icon name="check" size={11} /></span>}</div><progress value={transfer.progress} max={100} aria-label={`${transfer.name} 模拟传输进度`} /></div>)}<button className="deploy-button" onClick={() => props.notify('重新部署演示已准备就绪；真实部署服务尚未接入。')}><Icon name="upload" size={17} />重新部署</button></div></aside>;
}
