import { useEffect, useRef } from 'react';
import type { Host, SavedCommand, TerminalSession } from '../types';
import { categories } from '../data/mock';
import { Icon, IconButton } from './Ui';

function Prompt({ host, local }: { host?: Host; local: boolean }) {
  return <span className="terminal-prompt"><span>{local ? 'local' : `${host?.user ?? 'root'}@${host?.name ?? 'web-prod-01'}`}</span>:<span className="terminal-path">{local ? '~' : '/var/www/app'}</span>$ </span>;
}
export function TerminalWorkspace({ sessions, activeId, host, select, close, add, changeInput, run, fillFocus, maximize, isMaximized, notify }: { sessions: TerminalSession[]; activeId: string; host?: Host; select: (id: string) => void; close: (id: string) => void; add: () => void; changeInput: (text: string) => void; run: () => void; fillFocus: number; maximize: () => void; isMaximized: boolean; notify: (text: string) => void }) {
  const active = sessions.find(session => session.id === activeId);
  const inputRef = useRef<HTMLInputElement>(null);
  const scrollRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (fillFocus) inputRef.current?.focus(); }, [fillFocus]);
  useEffect(() => { if (scrollRef.current) scrollRef.current.scrollTop = scrollRef.current.scrollHeight; }, [active?.entries.length, activeId]);
  return <section className="terminal-workspace" aria-label="终端工作区"><div className="terminal-tabs" role="tablist" aria-label="终端会话">{sessions.map(session => <div className={`terminal-tab ${session.id === activeId ? 'selected' : ''}`} key={session.id}><button role="tab" aria-selected={session.id === activeId} onClick={() => select(session.id)}>{session.hostId ? <i className={`status-dot ${session.hostId === 'api' ? 'offline' : ''}`} /> : <Icon name="terminal" size={18} />}<span>{session.title}</span></button><IconButton icon="close" label={`关闭 ${session.title}`} onClick={() => close(session.id)} /></div>)}<IconButton icon="plus" label="新增终端" onClick={add} /></div>{active ? <div className="terminal-pane"><div className="terminal-toolbar"><span className="traffic-lights" aria-hidden="true"><i /><i /><i /></span><span>{active.hostId ? `${host?.user}@${host?.name}: /var/www/app` : 'local: ~'}</span><div className="inline-actions"><IconButton icon="split" label="分屏终端" onClick={() => notify('演示版本暂未接入终端分屏。')} /><IconButton icon={isMaximized ? 'split' : 'maximize'} label={isMaximized ? '恢复终端布局' : '最大化终端'} onClick={maximize} /></div></div><div className="terminal-output" ref={scrollRef}>{active.entries.map(entry => <div className="terminal-entry" key={entry.id}><div><Prompt host={host} local={!active.hostId} />{entry.command}</div><pre>{entry.output}</pre></div>)}{active.hostId && !host?.online && <p className="terminal-notice">主机离线，无法运行命令。</p>}<form className="terminal-input-row" onSubmit={e => { e.preventDefault(); run(); }}><label htmlFor="terminal-input"><Prompt host={host} local={!active.hostId} /></label><div className="terminal-input-wrap"><input id="terminal-input" ref={inputRef} value={active.input} aria-label="终端命令输入" autoComplete="off" spellCheck={false} disabled={active.busy || (!!active.hostId && !host?.online)} onChange={e => changeInput(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && e.nativeEvent.isComposing) e.preventDefault(); }} />{!active.input && !active.busy && <span className="block-cursor" />}</div>{active.busy && <span className="terminal-pending">模拟执行中…</span>}</form></div></div> : <div className="terminal-empty"><Icon name="terminal" size={38} /><h2>开始一个终端会话</h2><p>所有命令均在演示环境中运行</p><button className="primary-button" onClick={add}>新建终端</button></div>}</section>;
}
export function CommandShelf({ commands, category, setCategory, fill, run, copy, add, disabled, collapsed, toggleCollapsed }: { commands: SavedCommand[]; category: string; setCategory: (value: string) => void; fill: (command: string) => void; run: (command: string) => void; copy: (text: string) => void; add: () => void; disabled: boolean; collapsed: boolean; toggleCollapsed: () => void }) {
  const filtered = commands.filter(command => category === '全部' || command.category === category);
  return <section className={`command-shelf ${collapsed ? 'collapsed' : ''}`} id="commands" tabIndex={-1}><div className="section-heading"><button className="panel-title" onClick={toggleCollapsed} aria-expanded={!collapsed} title={collapsed ? '展开常用命令' : '收起常用命令'}><Icon name={collapsed ? 'right' : 'down'} size={14} /><h2>常用命令</h2><span className="panel-count">{commands.length}</span></button><button className="text-button" onClick={add}><Icon name="plus" />添加命令</button></div>{!collapsed && <><div className="command-categories" role="tablist" aria-label="命令分类">{categories.map(item => <button key={item} role="tab" aria-selected={category === item} className={category === item ? 'selected' : ''} onClick={() => setCategory(item)}>{item}</button>)}</div><div className="command-list">{filtered.map(command => <div className="command-row" key={command.id}><button className="command-fill" onClick={() => fill(command.command)} title={`填入命令：${command.command}`}><Icon name={command.icon} size={20} /><span className="command-name">{command.name}</span><code>{command.command}</code></button><button className="run-command labeled-run" aria-label={`运行 ${command.name}`} disabled={disabled} onClick={() => run(command.command)}><Icon name="play" size={14} />运行</button><IconButton icon="copy" label={`复制 ${command.name}`} onClick={() => copy(command.command)} /></div>)}{!filtered.length && <div className="empty-state">此分类暂无命令<button className="text-button mint" onClick={add}>添加第一条命令</button></div>}</div><p className="command-hint">点击命令可填入当前终端</p></>}</section>;
}
