// Requires Playwright and an installed Chrome. Start the Vite server first.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE_PATH || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');

(async () => {
  const output = path.resolve(process.env.AGENT_SSH_QA_DIR || 'artifacts/ui');
  await fs.mkdir(output, { recursive: true });
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const context = await browser.newContext({ viewport: { width: 1600, height: 1000 }, permissions: ['clipboard-read', 'clipboard-write'] });
  const page = await context.newPage();
  const errors = [];
  const checks = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  const check = (name, condition) => { assert.ok(condition, name); checks.push(name); console.log(`PASS ${name}`); };
  const waitFor = (callback) => page.waitForFunction(callback);
  const click = name => page.getByRole('button', { name, exact: true }).click();
  const close = () => click('关闭弹窗');
  const input = page.getByRole('textbox', { name: '终端命令输入', exact: true });
  try {
    await page.goto(process.env.AGENT_SSH_URL || 'http://127.0.0.1:1420/');
    await page.getByRole('heading', { name: '智能体' }).waitFor();
    for (const [width, height] of [[1600, 1000], [1440, 900], [1280, 800]]) {
      await page.setViewportSize({ width, height });
      await page.screenshot({ path: path.join(output, `${width}x${height}.png`) });
      const layout = await page.evaluate(() => ({
        overflow: document.documentElement.scrollWidth > innerWidth || document.documentElement.scrollHeight > innerHeight,
        center: document.querySelector('.central-workspace').getBoundingClientRect().width,
        send: document.querySelector('.send-button').getBoundingClientRect().right <= innerWidth,
        commands: [...document.querySelectorAll('.command-row')].every(row => row.getBoundingClientRect().bottom <= document.querySelector('.command-list').getBoundingClientRect().bottom + 1),
      }));
      check(`${width}x${height}: no page overflow, visible commands and composer`, !layout.overflow && layout.center >= 500 && layout.send && layout.commands);
    }
    await page.setViewportSize({ width: 1440, height: 900 });
    const theme = await page.evaluate(() => {
      const body = getComputedStyle(document.documentElement);
      const terminal = getComputedStyle(document.querySelector('.terminal-pane'));
      const terminalText = getComputedStyle(document.querySelector('.terminal-output'));
      const rgb = value => value.match(/\d+/g).slice(0, 3).map(Number);
      return { background: rgb(body.backgroundColor), bodyFont: parseFloat(body.fontSize), terminalBackground: rgb(terminal.backgroundColor), terminalFont: parseFloat(terminalText.fontSize) };
    });
    check('reference light shell and dark terminal applied', theme.background.reduce((a, b) => a + b, 0) > 650 && theme.terminalBackground.reduce((a, b) => a + b, 0) < 150 && theme.bodyFont <= 12 && theme.terminalFont <= 13);
    check('demo mode is always labelled', await page.getByText('演示模式', { exact: true }).isVisible());
    const terminalHeight = (await page.locator('.terminal-workspace').boundingBox()).height;
    await page.locator('.panel-title').click();
    check('command panel collapses and returns space to terminal', await page.locator('.command-row').count() === 0 && (await page.locator('.terminal-workspace').boundingBox()).height > terminalHeight);
    await page.locator('.panel-title').click();
    check('command panel expands with all default commands', await page.locator('.command-row').count() === 4);
    await page.getByRole('button', { name: /^新建连接/ }).click();
    check('new connection opens host chooser', await page.getByRole('dialog', { name: '连接主机' }).isVisible() && await page.locator('.connection-option').count() === 2);
    await page.keyboard.press('Escape');
    await page.getByRole('button', { name: /^打开文件/ }).click();
    await page.waitForFunction(() => document.activeElement?.id === 'files');
    check('open files focuses the file panel', true);
    await page.locator('.panel-title').click();
    await page.getByRole('button', { name: /^执行命令/ }).click();
    check('command shortcut restores collapsed shelf', await page.locator('.command-row').count() === 4);
    await click('刷新系统状态');
    check('system refresh gives mock feedback', (await page.getByRole('status').innerText()).includes('系统状态已更新'));
    await click('重新部署');
    check('redeploy explains demonstration scope', (await page.getByRole('status').innerText()).includes('真实部署服务尚未接入'));
    await page.getByTitle('填入命令：df -h').click();
    check('command fills current terminal', await input.inputValue() === 'df -h');
    await click('运行 磁盘使用');
    await page.getByRole('dialog', { name: '确认执行命令' }).waitFor();
    await click('取消');
    check('cancel preserves output and draft', await page.locator('.terminal-entry').count() === 0 && await input.inputValue() === 'df -h');
    await input.press('Enter');
    await click('确认执行');
    await waitFor(() => document.querySelectorAll('.terminal-entry').length === 1);
    check('confirmed command produces mock result', (await page.locator('.terminal-entry').last().innerText()).includes('35%'));
    await page.getByRole('switch', { name: '执行前确认', exact: true }).click();
    await input.fill('unsupported-demo-command');
    await input.press('Enter');
    await waitFor(() => document.querySelector('.terminal-output').textContent.includes('演示模式暂不支持此命令'));
    check('confirmation disabled and unknown command handled', await page.getByRole('dialog').count() === 0);
    await click('复制 容器状态');
    check('clipboard receives command', await page.evaluate(() => navigator.clipboard.readText()) === 'docker compose ps');
    await click('复制远程路径');
    check('clipboard receives path', await page.evaluate(() => navigator.clipboard.readText()) === '/var/www/app');
    await page.getByRole('tab', { name: 'Docker', exact: true }).click();
    check('category filters command list', await page.locator('.command-row').count() === 1);
    await page.getByRole('tab', { name: '部署', exact: true }).click();
    check('empty category shown', await page.getByText('此分类暂无命令', { exact: false }).isVisible());
    await click('添加命令');
    await click('保存命令');
    check('empty command form validated', await page.getByRole('alert').isVisible());
    await page.getByLabel('名称', { exact: true }).fill('部署检查');
    await page.getByLabel('分类', { exact: true }).selectOption('部署');
    await page.getByRole('textbox', { name: '命令', exact: true }).fill('echo deployment');
    await click('保存命令');
    check('new command saved and category selected', await page.getByText('部署检查', { exact: true }).isVisible());
    await page.keyboard.press('Control+k');
    await page.getByRole('combobox', { name: '搜索内容' }).fill('10.0.0.22');
    await page.getByRole('combobox', { name: '搜索内容' }).press('Enter');
    check('search selects offline host', await input.isDisabled());
    check('offline run action disabled', await page.getByRole('button', { name: '运行 部署检查', exact: true }).isDisabled());
    await page.keyboard.press('Control+k');
    await page.getByRole('combobox', { name: '搜索内容' }).fill('no-result-12345');
    check('search empty state', await page.getByText('没有找到匹配结果').isVisible());
    await page.getByRole('combobox', { name: '搜索内容' }).fill('web-prod');
    await page.getByRole('combobox', { name: '搜索内容' }).press('Enter');
    check('online host restores execution', await input.isEnabled());
    await page.keyboard.press('Control+k');
    await page.getByRole('combobox', { name: '搜索内容' }).fill('error.log');
    await page.getByRole('combobox', { name: '搜索内容' }).press('ArrowDown');
    await page.getByRole('combobox', { name: '搜索内容' }).press('Enter');
    check('keyboard search locates nested file', (await page.locator('.file-row.selected').innerText()).includes('error.log'));
    await click('logs');
    check('folder collapse', await page.getByRole('button', { name: 'access.log', exact: true }).count() === 0);
    await click('logs');
    check('folder expand', await page.getByRole('button', { name: 'access.log', exact: true }).isVisible());
    await click('新建');
    await page.getByLabel('名称', { exact: true }).fill('notes.txt');
    await click('创建');
    check('create in-memory file', await page.getByRole('button', { name: 'notes.txt', exact: true }).isVisible());
    await click('刷新文件树');
    check('refresh resets in-memory file tree', await page.getByRole('button', { name: 'notes.txt', exact: true }).count() === 0);
    await page.locator('input[type=file]').setInputFiles({ name: 'qa-upload.txt', mimeType: 'text/plain', buffer: Buffer.from('mock upload') });
    await page.waitForFunction(() => document.querySelector('progress[aria-label="qa-upload.txt 模拟传输进度"]')?.value === 100);
    check('mock upload completes', await page.getByText('qa-upload.txt', { exact: true }).isVisible());
    const chat = page.getByRole('textbox', { name: '智能体任务输入', exact: true });
    check('empty chat cannot send', await page.getByRole('button', { name: '发送消息', exact: true }).isDisabled());
    await chat.fill('检查服务');
    await chat.press('Shift+Enter');
    await chat.press('x');
    check('Shift+Enter inserts newline', (await chat.inputValue()).includes('\n'));
    await chat.fill('中文输入中');
    await chat.evaluate(el => el.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', code: 'Enter', isComposing: true, bubbles: true })));
    check('IME Enter does not send', await page.locator('.user-message').count() === 0);
    await chat.fill('检查磁盘');
    await chat.press('Enter');
    await waitFor(() => document.querySelectorAll('.assistant-message').length === 1);
    check('chat receives simulated reply', await page.locator('.user-message').count() === 1);
    await chat.fill('取消这条待完成回复');
    await chat.press('Enter');
    await click('新建对话');
    await page.waitForTimeout(1100);
    check('new chat cancels pending response', await page.locator('.assistant-message').count() === 0 && await page.locator('.user-message').count() === 0);
    await click('历史');
    check('execution history recorded', (await page.getByRole('dialog').innerText()).includes('unsupported-demo-command'));
    await close();
    await click('最大化终端');
    check('terminal maximizes', !(await page.locator('.agent-panel').isVisible()));
    await click('恢复终端布局');
    check('terminal restores', await page.locator('.agent-panel').isVisible());
    await page.getByRole('tab', { name: '本地终端', exact: true }).click();
    check('local terminal preserves its independent output', await page.locator('.terminal-entry').count() === 2);
    await input.fill('a'.repeat(500));
    check('long command remains inside viewport', await page.evaluate(() => document.documentElement.scrollWidth === innerWidth));
    await click('新增终端');
    check('new terminal starts empty', await input.inputValue() === '');
    while (await page.locator('.terminal-tab').count()) await page.locator('.terminal-tab .icon-button').first().click();
    check('all tabs closed shows new-session entry', await page.getByRole('button', { name: '新建终端', exact: true }).isVisible());
    await click('新建终端');
    check('new-session entry restores terminal', await input.isVisible());
    check('no browser console or runtime errors', errors.length === 0);
    await fs.writeFile(path.join(output, 'results.json'), JSON.stringify({ checks, errors }, null, 2));
    console.log(`Verified ${checks.length} checks. Screenshots: ${output}`);
  } catch (error) {
    await page.screenshot({ path: path.join(output, 'failure.png') });
    await fs.writeFile(path.join(output, 'failure.txt'), `${error.stack}\n${errors.join('\n')}`);
    throw error;
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
